#!/usr/bin/env python3

import os
import sys
import datetime
import json

# CGI Header
print("Content-Type: text/html\r")
print("\r")

# Get environment variables
method = os.environ.get('REQUEST_METHOD', 'GET')
uri = os.environ.get('REQUEST_URI', '/')
query = os.environ.get('QUERY_STRING', '')
content_length = int(os.environ.get('CONTENT_LENGTH', '0'))

# Read POST data if present
post_data = ""
if method == 'POST' and content_length > 0:
    post_data = sys.stdin.read(content_length)

print("""<!DOCTYPE html>
<html>
<head>
    <title>Python CGI Test</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 20px;
            background: linear-gradient(135deg, #a8e6cf, #dcedc8);
            min-height: 100vh;
        }
        .container {
            background: rgba(255, 255, 255, 0.9);
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        .info-box {
            background: #f8f9fa;
            padding: 15px;
            margin: 10px 0;
            border-radius: 8px;
            border-left: 4px solid #28a745;
        }
        .code {
            background: #f1f3f4;
            padding: 10px;
            border-radius: 4px;
            font-family: monospace;
            margin: 10px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐍 Python CGI Test - SUCCESS!</h1>
        <p>This page is generated by a Python CGI script.</p>
        
        <div class="info-box">
            <h2>📊 Request Information</h2>""")

print(f"            <p><strong>Method:</strong> {method}</p>")
print(f"            <p><strong>URI:</strong> {uri}</p>")
print(f"            <p><strong>Query String:</strong> {query}</p>")
print(f"            <p><strong>Content Length:</strong> {content_length}</p>")
print(f"            <p><strong>Server Time:</strong> {datetime.datetime.now()}</p>")

print("""        </div>
        
        <div class="info-box">
            <h2>🌍 Environment Variables</h2>
            <div class="code">""")

# Display important CGI environment variables
cgi_vars = ['REQUEST_METHOD', 'REQUEST_URI', 'QUERY_STRING', 'CONTENT_TYPE', 
           'CONTENT_LENGTH', 'SERVER_SOFTWARE', 'SERVER_NAME', 'SCRIPT_NAME',
           'HTTP_HOST', 'HTTP_USER_AGENT']

for var in cgi_vars:
    value = os.environ.get(var, 'Not set')
    print(f"{var}: {value}<br>")

print("""            </div>
        </div>""")

# Display POST data if present
if post_data:
    print("""        <div class="info-box">
            <h2>📝 POST Data</h2>
            <div class="code">""")
    print(f"Raw POST data: {post_data}")
    print("""            </div>
        </div>""")

# Display query parameters
if query:
    print("""        <div class="info-box">
            <h2>🔍 Query Parameters</h2>
            <div class="code">""")
    
    params = query.split('&')
    for param in params:
        if '=' in param:
            key, value = param.split('=', 1)
            print(f"{key}: {value}<br>")
        else:
            print(f"{param}: (no value)<br>")
    
    print("""            </div>
        </div>""")

print("""        
        <div class="info-box">
            <h2>🧪 Test Forms</h2>
            
            <h3>GET Test</h3>
            <form method="GET">
                <input type="text" name="python_test" placeholder="Enter test data">
                <input type="submit" value="Test GET">
            </form>

            <h3>POST Test</h3>
            <form method="POST">
                <input type="text" name="post_test" placeholder="Enter POST data">
                <input type="submit" value="Test POST">
            </form>
        </div>

        <div class="info-box">
            <h2>✅ Python CGI Status</h2>
            <p>✓ Python script execution: <span style="color: green;">Working</span></p>
            <p>✓ Environment variables: <span style="color: green;">Available</span></p>
            <p>✓ Standard input/output: <span style="color: green;">Functional</span></p>
            <p>✓ HTTP integration: <span style="color: green;">Complete</span></p>
        </div>

        <p style="text-align: center; margin-top: 30px;">
            <a href="/" style="color: #007bff; text-decoration: none;">← Back to Main Page</a>
        </p>
    </div>
</body>
</html>""")